
/*

	VALOR MÁXIMO EM UMA COLUNA DE DETERMINADA TABELA

*/

SELECT MAX (COLUNA) AS MAIOR_COLUNA FROM TABELA;

/*

MIN - VALOR MÍNIMO DE UMA COLUNA

*/

SELECT MIN (COLUNA) AS MENOR_COLUNA FROM TABELA;

/*

AVG -  VALOR MÉDIO
*/

SELECT AVG (COLUNA) AS MEDIA_COLUNA FROM TABELA;

/* VARIAS FUNÇÕES*/

SELECT MAX (COLUNA) AS NOME_PROJEÇÃO;
		MIN (COLUNA) AS NOME_PROJEÇÃO;
		AVG (COLUNA) AS NOME_PROJEÇÃO;
FROM TABELA;

/*TRUNQUEITE
ELA PEDE DOIS PARAMETROS, PARAMETRO 1(NUMERO)
PARAMETRO 2 (QUANTIDADE DE CASAS DECIMAIS QUE EU QUERO)

*/

SELECT MAX (COLUNA) AS NOME_PROJEÇÃO
		MIN (COLUNA) AS NOME_PROJEÇÃO
		TRUNCATE (AVG (COLUNA),2) AS NOME_PROJEÇÃO
FROM TABELA;

/*

SAM - SOMA OS VALORES DE UMA COLUNA

*/

SELECT SUM (COLUNA) AS NOME_PROJEÇÃO
FROM TABELA;

/*
	VENDAS POR SEXO

*/

SELECT SEXO, SUM (COLUNA) AS TOTAL_COLUNA
FROM TABELA
GROUP BY SEXO;

/*Subqueris*/

SELECT COLUNA, COLUNA FROM TABELA
WHERE COLUNA = (SELECT MIN (COLUNA) FROM TABELA);

/*

Calcular as linhas

*/

SELECT COLUNA,
		COLUNA,
		COLUNA
		(COLUNA+COLUNA+COLUNA) AS "TOTAL"
		(COLUNA+COLUNA+COLUNA) /3 AS "MÉDIA"
FROM TABELA;

/*

	APLICANDO %

*/