--ESTRUTURA DE UMA TRIGGER
--ALTERAR O DELIMITADOR

CREATE TRIGGER NOME
BEFORE/AFTER INSERT/DELETE/UPDATE ON TABELA
FOR EACH ROW (PARA CADA LINHA)
BEGIN -> INICIO


QUALQUER COMANDO SQL;


END->FIM
$

CREATE DATABASE AULA40;

USE AULA40;

CREATE TABLE USUARIO(
	IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	LOGIN VARCHAR(30),
	SENHA VARCHAR(100)
);

INSERT INTO USUARIO VALUES (NULL, "ANDRADE", "ANDRADE2009", "HEXACAMPEAO");

CREATE TABLE BKP_USUARIO(
	IDBACKUP INT PRIMARY KEY AUTO_INCREMENT,
	IDUSUARIO INT,
	NOME VARCHAR (30),
	LOGIN VARCHAR (30)
);

--CRIANDO A TRIGGER
--NEW - NOVO VALOR QUE ENTRA; OLD -- VALOR QUE JÁ EXISTE VELHO
-- EM UMA TABELA TEMOS 6 POSSIBILIDADES "ANTES E DEPOIS" NO INSERT,DELETE E UPDATE
DELIMITER $

CREATE TRIGGER BACKUP_USER
BEFORE DELETE ON USUARIO
FOR EACH ROW 
BEGIN 

	INSERT INTO BKP_USUARIO VALUES 
	(NULL,OLD.IDUSUARIO, OLD.NOME, OLD.LOGIN);



END
$

DELETE FROM USUARIO WHERE IDUSUARIO = 1;
SELECT  * FROM BKP_USUARIO;