/*PROCEDURES*/

/*
	No caso a estrutura ao criar uma procedured "bloco de programação", a regra de negócio estaria no Banco de dados, e captaria diretamente
	os dados de um formulário, por exemplo, e executaria no Banco. Pulando a camada de controler que estaria a programação (Em c# ou JAVA, JavaScript);

	DESENVOLVIMENTO (PROGRAMAR USANDO EM OUTRA LINGUAGEM) É UMA SUBDISCIPLINA
	
	BANCO DE DADOS SUBASSUNTOS (DESENVOLVER EM BANCO DE DADOS)
	PLSQL
	TSQL



*/

CREATE DATABASE PROJETO;

USE PROJETO;

CREATE TABLE CURSOS (
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR (30) NOT NULL,
	HORAS INT(3) NOT NULL,
	VALOR FLOAT (10,2) NOT NULL
);

INSERT INTO CURSOS VALUES (NULL, "JAVA",30,580.00);
INSERT INTO CURSOS VALUES (NULL, "SQL",40,320.00);

SELECT *FROM CURSOS;

DELIMITER $

STATUS

CREATE PROCEDURE CAD_CURSOS(P_NOME VARCHAR(30), 
							P_HORAS INT(3),
							P_PREÇO FLOAT(10,2))
BEGIN

	INSERT INTO CURSOS VALUES (NULL,P_NOME,P_HORAS,P_PREÇO);

END
$
/*

USAR O DELIMITER ALTERADO, NESSE CASO: $
DEVE-SE ALTERAR O DELIMITADOR POR MOTIVO DA
ELABORAÇÃO DO CÓDIGO, POIS O ";"É O PADRÃO 
E AO LER O BLOCO DE PROGRAMAÇÃO, ELE VAI DAR
ERRO.
*/

/*APÓS A PROGRAMAÇÃO RETORNA O DELIMITADOR AO PADRÃO*/
DELIMITER ;

CALL CAD_CURSOS("BI SQL SERVER",35,3000.00);
CALL CAD_CURSOS("POWER BI",55,4000.00);
CALL CAD_CURSOS("HTML",40,400.00);

SELECT *FROM CURSOS;