--ORGANIZAR FISICAMENTE E LOGICAMENTE UM BD

--1-CRIAR O BANCO COM ARQUIVOS PARA OS SETORES DE MKT E RH
--2-CRIAR UM ARQUIVO GERAL
--3 DEIXAR O MDF APENAS COM O DICIONÁRIO DE DADOS
--4-CRIAR OS 2 GRUPOS DE ARQUIVOS (PRIMARY - MDF)PADRÃO

CREATE TABLE EMPRESA (
	ID INT,
	NOME VARCHAR(50)
)
GO